services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./currencyApp:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn currencyApp.wsgi:application --bind 0.0.0.0:8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: currencyuser
      POSTGRES_PASSWORD: currencypass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static_volume:
