# Generated by Django 5.1.3 on 2025-05-18 19:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', message='Card number must be 16 digits.')])),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', message='CVV must be 3 or 4 digits.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'card_number'), name='unique_card_per_user'), models.CheckConstraint(condition=models.Q(('card_number__regex', '^\\d{16}$')), name='valid_card_number_format')],
            },
        ),
    ]
