# Generated by Django 5.1.3 on 2025-03-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrencyAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('PLN', 'Polish Zloty')], max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(editable=False, max_length=15, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_accounts', to='api.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'currency_code'), name='unique_user_currency_account')],
            },
        ),
    ]
