# Generated by Django 5.1.3 on 2025-05-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
