# Generated by Django 5.1.3 on 2025-05-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_withdrawhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secret_phrase',
            new_name='secret_key',
        ),
    ]
