# Generated by Django 5.1.3 on 2025-05-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_secret_phrase_user_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawhistory',
            name='currency',
        ),
        migrations.AddField(
            model_name='withdrawhistory',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('PLN', 'Polish Zloty')], default=0, max_length=3),
            preserve_default=False,
        ),
    ]
