# Generated by Django 5.1.3 on 2025-05-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_withdrawhistory_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawhistory',
            old_name='currency_code',
            new_name='currency',
        ),
    ]
